version: "3.7"

services:
  m1m20-abb:
    image: m1m20-testing/testing:0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/ABTLUS/rafael.cardoso/repos/modbusModule-ioc/ioc:/root/ioc
